spring.application.name=Employee Backend API

spring.datasource.url=jdbc:h2:mem:employeedb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# ===============================
# SERVER CONFIG
# ===============================
server.port=8080
server.shutdown=graceful




# ===============================
# LOGGING CONFIG
# ===============================
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.com.example.employee=DEBUG

# Log format (optional but useful)
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# ===============================
# API VERSION CONFIG
# ===============================
api.version=v1
api.enabled=true

# Path-based versioning: /api/v1/employees, /api/v2/employees, etc.

springdoc.api-docs.path=/api/v1/api-docs
springdoc.swagger-ui.path=/api/v1/swagger-ui.html